[package]
name = "lazyserial"
version = "0.1.0"
edition = "2021"
email="wu-felix@outlook.com"
description = "serial"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Wu-Felix/lazyserial.git"

[dependencies]
tokio = { version = '1.40.0', features = ["full"] }
bytes='1.7.2'
tokio-serial='5.4.4'
clap = { version = "4.5.20", features = ["derive"] }
